name: hydrate_app

description: "Aplicativo de lembrete de hidratação"

publish_to: 'none' #



version: 1.0.0+1



environment:

  sdk: '>=3.2.0 <4.0.0'



dependencies:
  
  sensors_plus: ^4.0.2

  rxdart: ^0.27.7

  flutter:

    sdk: flutter



  cupertino_icons: ^1.0.2

  flutter_local_notifications: ^15.1.2

  provider: ^6.1.1

  shared_preferences: ^2.2.2

  timezone: ^0.9.2



dev_dependencies:

  flutter_test:

    sdk: flutter



  flutter_lints: ^3.0.0





flutter:



  uses-material-design: true




